// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	indonesia_city_location "consignku/bussiness/indonesia_city_location"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Store provides a mock function with given fields: ctx, cityDomain
func (_m *Usecase) Store(ctx context.Context, cityDomain *indonesia_city_location.Domain) error {
	ret := _m.Called(ctx, cityDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *indonesia_city_location.Domain) error); ok {
		r0 = rf(ctx, cityDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
